import './globals.css'
import { Inter } from 'next/font/google'
import 'flowbite';
import Script from 'next/script';
import NavbarComponents from '@/components/NavbarComponents';
import FooterComponents from '@/components/FooterComponents';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Home page',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarComponents/>
        {children}
        <FooterComponents/>
        </body>
    </html>
  )
}
